### PR TITLE
fix for duplicate applying nodes

### LINKED ISSUE #132: duplicated, every-growing .status.applying on plans
See https://github.com/rancher/rancher/issues/32050#issuecomment-904762457

Caused by my last bugfix at https://github.com/rancher/system-upgrade-controller/commit/90e3d082a41fefaf09d14286b880c54a28af6c21#r55382218

### PR DESCRIPTION
**Pull request by dweomer**
Make duplicate entries for .status.applying on plans magically disappear
by correctly sorting the return value for SelectConcurrentNodes.

Fixes #132

Additionally, address a logic bug introduced in #126 that could also
spin out of control.

See
https://github.com/rancher/system-upgrade-controller/commit/90e3d082a41fefaf09d14286b880c54a28af6c21

Signed-off-by: Jacob Blain Christen <jacob@rancher.com>

### CODE REVIEW

**Comment by dweomer** [comment]
See also, https://github.com/rancher/rancher/issues/32050#issuecomment-904762457

File: pkg/upgrade/handle_upgrade.go [hunk 1]
```diff
@@ -74,7 +75,7 @@ func (ctl *Controller) handlePlans(ctx context.Context) error {
 			}
 			for _, node := range concurrentNodes {
 				objects = append(objects, upgradejob.New(obj, node, ctl.Name))
-				obj.Status.Applying = append(obj.Status.Applying, node.Name)
+				obj.Status.Applying = append(obj.Status.Applying, upgradenode.Hostname(node))
```
Comment (dweomer) [inline pkg/upgrade/handle_upgrade.go:78]: Addresses a logic bug introduced in #126 for the issue it purported to fix

File: pkg/upgrade/plan/plan.go [hunk 2]
```diff
@@ -177,7 +189,7 @@ func SelectConcurrentNodes(plan *upgradeapiv1.Plan, nodeCache corectlv1.NodeCach
 		}
 	}
 	sort.Slice(selected, func(i, j int) bool {
-		return selected[i].Name < selected[i].Name
+		return selected[i].Name < selected[j].Name
```
Comment (dweomer) [inline pkg/upgrade/plan/plan.go:192]: Amazing!

**Review by kinarashah — APPROVED** [review]

**Review by brandond — APPROVED** [review]

File: pkg/upgrade/handle_upgrade.go (hunk 1 above)
Comment (dweomer) [reply pkg/upgrade/handle_upgrade.go:78]: OMG :man_facepalming:

**Review by kinarashah — APPROVED** [review]

File: pkg/upgrade/handle_upgrade.go [hunk 3]
```diff
@@ -72,10 +73,13 @@ func (ctl *Controller) handlePlans(ctx context.Context) error {
...
 			}
-			for _, node := range concurrentNodes {
+			concurrentNodeNames := make([]string, len(concurrentNodes))
+			for i := range concurrentNodes {
+				node := concurrentNodes[i]
 				objects = append(objects, upgradejob.New(obj, node, ctl.Name))
-				obj.Status.Applying = append(obj.Status.Applying, node.Name)
+				concurrentNodeNames[i] = upgradenode.Hostname(node)
 			}
+			obj.Status.Applying = concurrentNodeNames[:]
```
Comment (dweomer) [inline pkg/upgrade/handle_upgrade.go:82]: The sort issue was spurious, this was where the dupes were coming from all along.
